#!/bin/bash

set -x
set -e

./mvnw clean package -P prod -DSPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT-URI=https://ytapp-339922-crzmcsu6ea-uc.a.run.app/login/oauth2/code/google
docker rm -f ytapp
docker build . -t ytapp:latest
docker run -p 8081:8080 -p 8082:8081 \
        --name ytapp \
        --memory="1G" \
        ytapp:latest
