#!/bin/bash

set -x
set -e

./mvnw clean package -P quick
docker rm -f signup2
docker build . -t signup2:latest
docker run -p 8081:8080 -p 8082:8081 \
        --network ebiz-signup2_default \
        --name signup2 \
        --memory="1G" \
        signup2:latest
