#!/bin/bash

set -x
set -e

./mvnw clean package
docker rm -f ytapp
docker build . -t ytapp:latest
docker run -p 8081:8080 -p 8082:8081 \
        --name ytapp \
        --memory="1G" \
        ytapp:latest
