name: CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: thedariusz/ytapp

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Test
        run: ./mvnw verify

      - name: Package
        run: ./mvnw package

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          ./mvnw package
          docker build . -t ${DOCKER_IMAGE_NAME}:${GITHUB_SHA::7}

      - name: Publish Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ${DOCKER_IMAGE_NAME}:${GITHUB_SHA::7}